Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
  config.vm.provision "shell", inline: <<-SHELL
  sudo systemctl stop firewalld
  sudo yum install -y git centos-release-ansible-29.noarch
  sudo yum install -y ansible
  sudo yum install -y epel-release
  sudo yum install -y python2-pip
  sudo yum install -y python2-jmespath
  cd /usr/local && sudo git clone https://github.com/RamSailopal/YottaDB-dashboard.git
  sudo ansible-galaxy install ramsailopal.yottadb ramsailopal.yottadb_nodejs ramsailopal.yottadb_dashboard_role ramsailopal.yottadb_apiserver patrickjahns.promtail cloudalchemy.grafana cloudalchemy.prometheus
  sudo ansible-galaxy collection install community.grafana
  sudo bash -c 'echo -e "  [localhost]\n  127.0.0.1" >> "/etc/ansible/hosts"'
  sudo ssh-keygen -N "" -f /root/.ssh/id_rsa
  sudo cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
  sudo bash -c 'echo "StrictHostKeyChecking no" >> "/root/.ssh/config"'
  sudo ansible-playbook -e grafhost="127.0.0.1" -e grafpass="test" -e dashport="8001" -e apiport="8002" -e repodir="/usr/local/YottaDB-dashboard" -e mgateway="yes" -e force="Yes" /usr/local/YottaDB-dashboard/Ansible/install.yaml
  sudo yum install -y python3
  sudo pip3.6 install prometheus_client
  sudo pip3.6 install xmltodict
  sudo bash -c 'cd /usr/local/YottaDB-dashboard && ./install.sh /root/.yottadb/r1.32_x86_64/r'
  sudo sed -i 's@^#!/usr/bin/python@#!/usr/bin/python3.6@' /usr/local/YottaDB-dashboard/ydbdash.py
  sudo bash -c 'export YOTTA_PROM_PORT="8001" && export PATH="$PATH:/usr/local/bin" && export ydb_rel="r1.32_x86_64" && export yotta_dir="/root/.yottadb" && cd /usr/local/YottaDB-dashboard && ./ydbdash.sh "stop" && ./ydbdash.sh "start"'
  sudo sed -i 's@^#!/usr/bin/python@#!/usr/bin/python3.6@' /usr/local/YottaDB-dashboard/apiserver/apiserver.py
  sudo bash -c 'export YOTTA_API_PORT="8002" && export YOTTA_API_IP="0.0.0.0" && export PATH="$PATH:/usr/local/bin" && export yotta_dir="/root/.yottadb" && export yotta_instdir="/usr/local/yottadb" && export ydb_dir="/root/.yottadb" && export ydb_rel="r1.32_x86_64" && export ydb_gbldir="/root/.yottadb/r1.32_x86_64/g/yottadb" && cd /usr/local/YottaDB-dashboard/apiserver && ./apiserver.sh "stop" && ./apiserver.sh "start"'
  SHELL
  end
