#
#       AUTHOR - Raman Sailopal
#
#       docker compose yml file for the YottaDB-Dashboard stack
#
version: "2"
services:
 vista:
   image: docker.io/vistadataproject/nodevista999
   ports:
      - 9330:9430 
      - 32:22 
      - 9100:9000 
      - 9331:8001
   networks:
      - yottanet
   ipc: sharable
   pid: host
   volumes:
     - "$yottadatadir:/home/nodevista"
 yottadbdash:
   image: docker.io/ramb0/vistadash
   ports:
      - 8083:8083
   networks:
      - yottanet
   ipc: sharable
   pid: host
   environment:
     - YOTTA_PROM_PORT=8083
   volumes:
     - "$yottadatadir:/home/nodevista"
 yottaapi:
   image: docker.io/ramb0/vista-apiserv
   ports:
      - 8082:8082
   networks:
      - yottanet
   ipc: sharable
   pid: host
   environment:
     - API_PORT=8082
     - API_SERVER=0.0.0.0
     - yotta_dir=/home
     - yotta_instdir=/home/nodevista/lib/gtm
     - ydb_dir=/home
     - ydb_rel=nodevista
     - ydb_gbl=/home/nodevista/g/nodevista
   volumes:
     - "$yottadatadir:/data"
 prometheus:
   image: docker.io/bitnami/prometheus
   volumes:
      - "$PWD/prometheus:/opt/bitnami/prometheus/conf"
   ports:
      - 9081:9090
   networks:
      - yottanet
 grafana:
   image: docker.io/grafana/grafana
   volumes:
      - "$PWD/provisioning:/etc/grafana/provisioning"
   ports: 
      - 3001:3000
   networks:
      - yottanet
   environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
networks:
    yottanet:
