Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 3001, host: 3001, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 9100, host: 9100, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8083, host: 8083, host_ip: "127.0.0.1"
  config.vm.provision "shell", inline: <<-SHELL
  sudo systemctl stop firewalld
  sudo yum install -y epel-release
  sudo yum install -y docker
  sudo yum install -y docker-compose
  sudo yum install -y git
  sudo systemctl start docker
  cd /usr/local && sudo git clone https://github.com/RamSailopal/YottaDB-dashboard.git
  cd /usr/local/YottaDB-dashboard/Vista-Docker && docker-compose up -d
  SHELL
  end
